In [29]:
import pandas as pd
import numpy as np

In [30]:
dataset = pd.read_csv(r"C:\Users\Himanshu\OneDrive\Desktop\SBI loan dataset 111\SBI loan dataset\train_u6lujuX_CVtuZ9i.csv")

In [31]:
dataset.head(10)

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
5,LP001011,Male,Yes,2,Graduate,Yes,5417,4196.0,267.0,360.0,1.0,Urban,Y
6,LP001013,Male,Yes,0,Not Graduate,No,2333,1516.0,95.0,360.0,1.0,Urban,Y
7,LP001014,Male,Yes,3+,Graduate,No,3036,2504.0,158.0,360.0,0.0,Semiurban,N
8,LP001018,Male,Yes,2,Graduate,No,4006,1526.0,168.0,360.0,1.0,Urban,Y
9,LP001020,Male,Yes,1,Graduate,No,12841,10968.0,349.0,360.0,1.0,Semiurban,N

In [32]:
dataset.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [33]:
dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)

C:\Users\Himanshu\AppData\Local\Temp\ipykernel_9168\3181356174.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Gender"].fillna(dataset["Gender"].mode()[0],inplace=True)

In [34]:
dataset["Married"].fillna(dataset["Married"].mode()[0],inplace=True)

C:\Users\Himanshu\AppData\Local\Temp\ipykernel_9168\3070595742.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dataset["Married"].fillna(dataset["Married"].mode()[0],inplace=True)

In [35]:
dataset.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [36]:
en_data = dataset[["Gender","Married"]]

In [37]:
pd.get_dummies(en_data)

     Gender_Female  Gender_Male  Married_No  Married_Yes
0            False         True        True        False
1            False         True       False         True
2            False         True       False         True
3            False         True       False         True
4            False         True        True        False
..             ...          ...         ...          ...
609           True        False        True        False
610          False         True       False         True
611          False         True       False         True
612          False         True       False         True
613           True        False        True        False

[614 rows x 4 columns]

In [38]:
pd.get_dummies(en_data).info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 614 entries, 0 to 613
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender_Female  614 non-null    bool
 1   Gender_Male    614 non-null    bool
 2   Married_No     614 non-null    bool
 3   Married_Yes    614 non-null    bool
dtypes: bool(4)
memory usage: 2.5 KB

In [39]:
from sklearn.preprocessing import OneHotEncoder

In [40]:
ohe = OneHotEncoder()

In [41]:
ohe.fit_transform(en_data)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1228 stored elements and shape (614, 4)>

In [42]:
ohe.fit_transform(en_data).toarray()

array([[0., 1., 1., 0.],
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       ...,
       [0., 1., 0., 1.],
       [0., 1., 0., 1.],
       [1., 0., 1., 0.]])

In [43]:
ohe = OneHotEncoder()
ar = ohe.fit_transform(en_data).toarray()

In [44]:
pd.DataFrame(ar,columns = ["Gender_Female","Gender_Male","Married_No","Married_yes"])

     Gender_Female  Gender_Male  Married_No  Married_yes
0              0.0          1.0         1.0          0.0
1              0.0          1.0         0.0          1.0
2              0.0          1.0         0.0          1.0
3              0.0          1.0         0.0          1.0
4              0.0          1.0         1.0          0.0
..             ...          ...         ...          ...
609            1.0          0.0         1.0          0.0
610            0.0          1.0         0.0          1.0
611            0.0          1.0         0.0          1.0
612            0.0          1.0         0.0          1.0
613            1.0          0.0         1.0          0.0

[614 rows x 4 columns]

In [45]:
ohe = OneHotEncoder(drop = "first")

In [47]:
ar = ohe.fit_transform(en_data).toarray()

In [48]:
pd.DataFrame(ar,columns = ["Gender_Male","Married_yes"])

     Gender_Male  Married_yes
0            1.0          0.0
1            1.0          1.0
2            1.0          1.0
3            1.0          1.0
4            1.0          0.0
..           ...          ...
609          0.0          0.0
610          1.0          1.0
611          1.0          1.0
612          1.0          1.0
613          0.0          0.0

[614 rows x 2 columns]